In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [11]:
a=np.arange(1,13)
print(a.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
a=np.array([[2,4,6], [3,7,9]])
print(a.shape)
print(a.size)

(2, 3)
6


In [14]:
a=np.linspace(1,20,8)
print(a)

[ 1.          3.71428571  6.42857143  9.14285714 11.85714286 14.57142857
 17.28571429 20.        ]


In [15]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
a=np.full((2,2),8)
print(a)

[[8 8]
 [8 8]]


In [17]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a.T)

(2, 3)
2
6
int64
[[1 4]
 [2 5]
 [3 6]]


In [18]:

arr = np.array([
    [[10, 20, 30],
     [40, 50, 60]],

    [[70, 80, 90],
     [100, 110, 120]]
])

print(arr)
print(arr.ndim)   # Number of dimensions
print(arr.shape)  # (Layers, Rows, Columns)
print(arr.size)   # Total number of elements
print(arr[0])        # First layer
print(arr[1])        # Second layer
print(arr[0][1])     # Second row of first layer
print(arr[1][0][0])  # Element 9

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
3
(2, 2, 3)
12
[[10 20 30]
 [40 50 60]]
[[ 70  80  90]
 [100 110 120]]
[40 50 60]
70


In [19]:
import numpy as np
arr = np.array([11, 12, 13, 14, 15, 16])
new_arr = arr.reshape(2, 3)
print(new_arr)

[[11 12 13]
 [14 15 16]]


In [20]:
arr_3d = np.array([1,2,3,4,5,6,7,8])
new_arr_3d = arr_3d.reshape(2,2,2)
print(new_arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[1:5])
print(arr[:4])
print(arr[2:])
print(arr[::2])

[20 30 40 50]
[10 20 30 40]
[30 40 50 60]
[10 30 50]


In [22]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr[0:2,1:3])
print(arr[1,:])
print(arr[:,2])

[[2 3]
 [5 6]]
[4 5 6]
[3 6 9]


In [23]:
import numpy as np
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(arr[0,:,:])
print(arr[1,1,:])
print(arr[:,:,0])

[[1 2 3]
 [4 5 6]]
[10 11 12]
[[ 1  4]
 [ 7 10]]


In [24]:
import numpy as np

a = np.array([1,2,3])
b = np.array([2,4,5])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Floor Division:", a//b)
print("Modulus:", a%b)
print("Power:", a**2)

Addition: [3 6 8]
Subtraction: [-1 -2 -2]
Multiplication: [ 2  8 15]
Division: [0.5 0.5 0.6]
Floor Division: [0 0 0]
Modulus: [1 2 3]
Power: [1 4 9]


In [25]:
import numpy as np

# Create a NumPy array
marks = np.array([75, 82, 90, 68, 95, 88, 79])

print("Original Array:", marks)
# Sort
print("Sorted Array:", np.sort(marks))
# Sum
print("\nSum:", np.sum(marks))

# Mean (Average)
print("Mean:", np.mean(marks))

# Median
print("Median:", np.median(marks))

# Maximum Value
print("Maximum:", np.max(marks))

# Minimum Value
print("Minimum:", np.min(marks))

# Range
print("Range:", np.ptp(marks))

# Standard Deviation
print("Standard Deviation:", np.std(marks))

# Variance
print("Variance:", np.var(marks))

# Index of Maximum Value
print("Index of Maximum:", np.argmax(marks))

# Index of Minimum Value
print("Index of Minimum:", np.argmin(marks))

# Percentiles
print("25th Percentile:", np.percentile(marks, 25))
print("50th Percentile:", np.percentile(marks, 50))
print("75th Percentile:", np.percentile(marks, 75))

Original Array: [75 82 90 68 95 88 79]
Sorted Array: [68 75 79 82 88 90 95]

Sum: 577
Mean: 82.42857142857143
Median: 82.0
Maximum: 95
Minimum: 68
Range: 27
Standard Deviation: 8.633111388421788
Variance: 74.53061224489797
Index of Maximum: 4
Index of Minimum: 3
25th Percentile: 77.0
50th Percentile: 82.0
75th Percentile: 89.0


In [26]:
import numpy as np
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr)
# Square Root
print("\nSquare Root:", np.sqrt(arr))
# Square
print("Square:", np.square(arr))
# Cube (Power 3)
print("Cube:", np.power(arr, 3))
# Absolute Value
arr2 = np.array([-5, -10, 15, -20, 25])
print("\nAbsolute Value:", np.abs(arr2))
# Exponential (e^x)
print("\nExponential:", np.exp(arr))
# Natural Logarithm
print("\nNatural Log:", np.log(arr))
# Base-10 Logarithm
print("Log Base 10:", np.log10(arr))
# Sine
print("\nSine:", np.sin(arr))
# Cosine
print("Cosine:", np.cos(arr))
# Tangent
print("Tangent:", np.tan(arr))
# Round Values
decimal = np.array([2.34, 4.67, 8.91, 6.28])
print("\nRounded Values:", np.round(decimal))
# Ceiling
print("Ceiling:", np.ceil(decimal))
# Floor
print("Floor:", np.floor(decimal))

Original Array: [1 2 3 4 5]

Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Square: [ 1  4  9 16 25]
Cube: [  1   8  27  64 125]

Absolute Value: [ 5 10 15 20 25]

Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

Natural Log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Log Base 10: [0.         0.30103    0.47712125 0.60205999 0.69897   ]

Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cosine: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Tangent: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]

Rounded Values: [2. 5. 9. 6.]
Ceiling: [3. 5. 9. 7.]
Floor: [2. 4. 8. 6.]


In [ ]:
import numpy as np

# Random number
print(np.random.rand())

# Random numbers
print(np.random.rand(5))

# Random integers
print(np.random.randint(1, 11, 5))

# Random choice
subjects = ["DBMS", "Python", "Java", "ML"]
print(np.random.choice(subjects))

# Normal distribution
print(np.random.normal(50, 10, 5))

# Uniform distribution
print(np.random.uniform(10, 20, 5))

# Bernoulli random variable
print(np.random.binomial(1, 0.5))

# Binomial random variable
print(np.random.binomial(10, 0.7))

# Poisson random variable
print(np.random.poisson(4, 5))

# Exponential random variable
print(np.random.exponential(2, 5))

In [28]:
import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as plt

np.set_printoptions(precision=3, suppress=True)
np.random.seed(42)
print('Setup complete. NumPy', np.__version__)

Setup complete. NumPy 2.0.2


In [29]:
A = np.arange(6).reshape(2, 3)
B = np.ones((2, 3), dtype=int)

print('A:\n', A)
print('A + B (element-wise add):\n', A + B)
print('A.T  (transpose -> shape', A.T.shape, '):\n', A.T)
print('A.reshape(3, 2):\n', A.reshape(3, 2))
print('A.flatten():', A.flatten())

A:
 [[0 1 2]
 [3 4 5]]
A + B (element-wise add):
 [[1 2 3]
 [4 5 6]]
A.T  (transpose -> shape (3, 2) ):
 [[0 3]
 [1 4]
 [2 5]]
A.reshape(3, 2):
 [[0 1]
 [2 3]
 [4 5]]
A.flatten(): [0 1 2 3 4 5]


In [34]:
T = np.arange(12).reshape(3, 4)
print('T:\n', T)

# 1. ndim and shape
print('Dimensions:', T.ndim)
print('Shape:', T.shape)

# 2. T + T
print('Sum:\n', T + T)

# 3. Transpose (print .T.shape) and reshape to (2, 6)
print('Transpose Shape:', T.T.shape)
print('Reshaped:\n', T.reshape(2, 6))


T:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Dimensions: 2
Shape: (3, 4)
Sum:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
Transpose Shape: (4, 3)
Reshaped:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [33]:
a = np.array([1, 2, 3])
b = np.array([4, 0, 1])
print('a . b  (dot)   :', np.dot(a, b))
print('a x b  (cross) :', np.cross(a, b))

a . b  (dot)   : 7
a x b  (cross) : [ 2 11 -8]


In [35]:
import numpy as np
import numpy.linalg as la
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('L2 norm  ||a||_2 :', la.norm(a))
print('L1 norm  ||a||_1 :', la.norm(a, 1))
print('Linf norm        :', la.norm(a, np.inf))
def cosine(u, v):
    return np.dot(u, v) / (la.norm(u) * la.norm(v))

print('cosine(a, b)     :', round(cosine(a, b), 3))


L2 norm  ||a||_2 : 3.7416573867739413
L1 norm  ||a||_1 : 6.0
Linf norm        : 3.0
cosine(a, b)     : 0.975


In [36]:
pairs = [
    (np.array([1, 0, 1]), np.array([1, 0, 1])),    # pair 1
    (np.array([1, 2, 3]), np.array([3, 2, 1])),    # pair 2
    (np.array([2, 0, 0]), np.array([0, 5, 0])),    # pair 3
]

def cosine(u, v):
    return np.dot(u, v) / (la.norm(u) * la.norm(v))

for i, (u, v) in enumerate(pairs, start=1):

    l1_norm = la.norm(u, 1)
    l2_norm = la.norm(u)

    # 2. cosine similarity of u and v
    similarity = cosine(u, v)

    print(f"Pair {i} -> U_L1: {l1_norm:.2f} | U_L2: {l2_norm:.2f} | Cosine Similarity: {similarity:.3f}")

# 3. Most similar pair = pair 1 (identical directional vectors, cosine similarity = 1.0)


Pair 1 -> U_L1: 2.00 | U_L2: 1.41 | Cosine Similarity: 1.000
Pair 2 -> U_L1: 6.00 | U_L2: 3.74 | Cosine Similarity: 0.714
Pair 3 -> U_L1: 2.00 | U_L2: 2.00 | Cosine Similarity: 0.000
